version: "3.8"

services:
    lexmedica-chatbot:
        container_name: lexmedica-chatbot
        build: .
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - REDIS_URL=redis://default:NGQrDDRfRBzXmzQYSiqh0WnXW2g4ZHQw@redis-16305.c44.us-east-1-2.ec2.redns.redis-cloud.com:16305
            - PORT=8080
        volumes:
            - .:/app
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 3
